#!groovy

// Generated by IBM TransformationAdvisor
// Wed Feb 13 19:15:06 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresortswar'
    mvnCommands = '--version'
    test='false'
}